# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import sponsorship.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'tr', 'Turkish'), (b'en', 'English')], max_length=2)),
                ('sponsor_type', models.CharField(choices=[(b'platin', 'Platin'), (b'gold', 'Gold'), (b'silver', 'Silver'), (b'bronze', 'Bronze'), (b'service', 'Service'), (b'media', 'Media')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to=sponsorship.models.get_upload_path)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
