# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'en', 'English'), (b'tr', 'Turkish')], max_length=2)),
                ('title', models.CharField(choices=[(b'general_photos', 'General Photos'), (b'all_categories', 'All Categories'), (b'sponsorship', 'Sponsorship'), (b'line_follower', 'Line Follower'), (b'basketball', 'Basketball'), (b'micro_sumo', 'Micro Sumo'), (b'fire_fighter', 'Fire Fighter'), (b'stair_climbing', 'Stair Climbing'), (b'maze', 'Maze'), (b'color_selecting', 'Color Selecting'), (b'self_balancing', 'Self Balancing'), (b'scenario', 'Scenario'), (b'innovative', 'Innovative')], max_length=50)),
                ('uid', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'en', 'English'), (b'tr', 'Turkish')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('uid', models.PositiveSmallIntegerField()),
                ('img', models.ImageField(upload_to=gallery.models.get_image_upload_path)),
                ('thumbnail', models.ImageField(upload_to=gallery.models.get_thumbnail_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery')),
            ],
        ),
    ]
