# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160210_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_divided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(choices=[(b'general_photos', 'ITURO General'), (b'all_categories', 'All Categories'), (b'sponsorship', 'Sponsorship'), (b'news', 'News'), (b'line_follower', 'Line Follower'), (b'basketball', 'Basketball'), (b'micro_sumo', 'Micro Sumo'), (b'fire_fighter', 'Fire Fighter'), (b'stair_climbing', 'Stair Climbing'), (b'maze', 'Maze'), (b'color_selecting', 'Color Selecting'), (b'self_balancing', 'Self Balancing'), (b'scenario', 'Scenario'), (b'innovative', 'Innovative')], max_length=50),
        ),
    ]
