# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160213_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
