# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20160220_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='new_slug',
            new_name='slug',
        ),
    ]
