# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160217_1305'),
        ('gallery', '0007_auto_20160220_0920'),
    ]

    operations = [
    ]
