# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20160220_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo'),
            preserve_default=False,
        ),
    ]
