# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20160302_2231'),
        ('gallery', '0008_merge'),
    ]

    operations = [
    ]
