# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 14:46
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'tr', 'Turkish'), (b'en', 'English')], max_length=2)),
                ('category', models.CharField(choices=[(b'line_follower', 'Line Follower'), (b'micro_sumo', 'Micro Sumo'), (b'fire_fighter', 'Fire Fighter'), (b'basketball', 'Basketball'), (b'stair_climbing', 'Stair Climbing'), (b'maze', 'Maze'), (b'color_selecting', 'Color Selecting'), (b'self_balancing', 'Self Balancing'), (b'scenario', 'Scenario'), (b'innovative', 'Innovative')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to=pages.models.get_file_upload_path)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='CommonEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'tr', 'Turkish'), (b'en', 'English')], max_length=2)),
                ('page', models.CharField(choices=[(b'common_knowlodge', 'Common Knowledge And Purposes'), (b'team', 'Organization Team'), (b'club', 'Control And Automation Club'), (b'past_organizations', 'Past Organizations'), (b'media', 'Media'), (b'faq', 'Frequently Asked Questions'), (b'common_rules', 'Common Rules'), (b'organization_rules', 'Organization Rules'), (b'home', 'Home')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'tr', 'Turkish'), (b'en', 'English')], max_length=2)),
                ('page', models.CharField(choices=[(b'common_knowlodge', 'Common Knowledge And Purposes'), (b'team', 'Organization Team'), (b'club', 'Control And Automation Club'), (b'past_organizations', 'Past Organizations'), (b'media', 'Media'), (b'faq', 'Frequently Asked Questions'), (b'common_rules', 'Common Rules'), (b'organization_rules', 'Organization Rules'), (b'home', 'Home')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.CommonEntry')),
            ],
        ),
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'tr', 'Turkish'), (b'en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(upload_to=pages.models.get_image_upload_path)),
                ('category', models.CharField(choices=[(b'danger', 'Caution'), (b'info', 'Info'), (b'success', 'Happy')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
