# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_categoryentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonentry',
            name='page',
            field=models.CharField(choices=[(b'common_knowlodge', 'Common Knowledge And Purposes'), (b'team', 'Organization Team'), (b'club', 'Control And Automation Club'), (b'past_organizations', 'Past Organizations'), (b'media', 'Media'), (b'faq', 'Frequently Asked Questions'), (b'common_rules', 'Common Rules'), (b'organization_rules', 'Organization Rules'), (b'past_sponsors', 'Past Sponsors'), (b'home', 'Home')], max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='page',
            field=models.CharField(choices=[(b'common_knowlodge', 'Common Knowledge And Purposes'), (b'team', 'Organization Team'), (b'club', 'Control And Automation Club'), (b'past_organizations', 'Past Organizations'), (b'media', 'Media'), (b'faq', 'Frequently Asked Questions'), (b'common_rules', 'Common Rules'), (b'organization_rules', 'Organization Rules'), (b'past_sponsors', 'Past Sponsors'), (b'home', 'Home')], max_length=100),
        ),
    ]
