# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:55
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'en', 'English'), (b'tr', 'Turkish')], max_length=2)),
                ('title', models.CharField(choices=[(b'general_information', 'General Informations and Our Purposes'), (b'team', 'ITURO Team'), (b'club', 'Control and Automation Club'), (b'previous_organizations', 'Previous ITUROs'), (b'media', 'Media')], max_length=50)),
                ('uid', models.PositiveSmallIntegerField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'en', 'English'), (b'tr', 'Turkish')], max_length=2)),
                ('title', models.CharField(choices=[(b'line_follower', 'Line Follower'), (b'basketball', 'Basketball'), (b'micro_sumo', 'Micro Sumo'), (b'fire_fighter', 'Fire Fighter'), (b'stair_climbing', 'Stair Climbing'), (b'maze', 'Maze'), (b'color_selecting', 'Color Selecting'), (b'self_balancing', 'Self Balancing'), (b'scenario', 'Scenario'), (b'innovative', 'Innovative')], max_length=50)),
                ('uid', models.PositiveSmallIntegerField()),
                ('document', models.FileField(upload_to=post.models.get_upload_path)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='CommonEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'en', 'English'), (b'tr', 'Turkish')], max_length=2)),
                ('title', models.CharField(choices=[(b'contact', 'Contact'), (b'faq', 'FAQ')], max_length=50)),
                ('uid', models.PositiveSmallIntegerField()),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'en', 'English'), (b'tr', 'Turkish')], max_length=2)),
                ('title', models.CharField(max_length=50)),
                ('uid', models.PositiveSmallIntegerField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'en', 'English'), (b'tr', 'Turkish')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('uid', models.PositiveSmallIntegerField()),
                ('types', models.CharField(choices=[(b'danger', 'Hot!'), (b'info', 'Information'), (b'primary', 'Important')], max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'en', 'English'), (b'tr', 'Turkish')], max_length=2)),
                ('title', models.CharField(choices=[(b'sponsors', 'Sponsors'), (b'previous_sponsors', 'Previous Sponsors'), (b'about_sponsorship', 'About Sponsorship')], max_length=50)),
                ('uid', models.PositiveSmallIntegerField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
