# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 19:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='url_content',
            field=ckeditor.fields.RichTextField(default='asd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutentry',
            name='title',
            field=models.CharField(choices=[(b'general_information', 'General Informations and Our Purposes'), (b'team', 'ITURO Team'), (b'club', 'Control and Automation Club'), (b'previous_organizations', 'Previous ITUROs'), (b'media', 'Media'), (b'general_rules', 'General Rules')], max_length=50),
        ),
        migrations.AlterField(
            model_name='categoryentry',
            name='title',
            field=models.CharField(choices=[(b'line_follower', 'Line Follower'), (b'basketball', 'Basketball'), (b'micro_sumo', 'Micro Sumo'), (b'fire_fighter', 'Fire Fighter'), (b'stair_climbing', 'Stair Climbing'), (b'maze', 'Maze'), (b'color_selecting', 'Color Selecting'), (b'self_balancing', 'Self Balancing'), (b'scenario', 'Scenario'), (b'innovative', 'Innovative'), (b'higher_category_rules', 'Higher Category Rules')], max_length=50),
        ),
    ]
