# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160210_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryentry',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonentry',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageentry',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorshipentry',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
