# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160210_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutentry',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
