# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_aboutentry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='short_description',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
