# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_newsentry_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutentry',
            name='is_divided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutentry',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryentry',
            name='is_divided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryentry',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonentry',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorshipentry',
            name='is_divided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorshipentry',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
