# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20160211_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutentry',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='categoryentry',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sponsorshipentry',
            options={'ordering': ['order']},
        ),
    ]
