# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20160213_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutentry',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryentry',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryentry',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commonentry',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commonentry',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsorshipentry',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsorshipentry',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
