# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20160213_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commonentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorshipentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
