# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20160213_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsentry',
            name='short_description',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
