# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20160220_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryentry',
            old_name='slug',
            new_name='new_slug',
        ),
        migrations.RenameField(
            model_name='commonentry',
            old_name='slug',
            new_name='new_slug',
        ),
        migrations.RenameField(
            model_name='sponsorshipentry',
            old_name='slug',
            new_name='new_slug',
        ),
        migrations.RemoveField(
            model_name='aboutentry',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='homepageentry',
            name='slug',
        ),
        migrations.AddField(
            model_name='aboutentry',
            name='new_slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutentry',
            name='old_slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryentry',
            name='old_slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonentry',
            name='old_slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorshipentry',
            name='old_slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
