# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20160220_1201'),
        ('post', '0010_auto_20160217_1305'),
    ]

    operations = [
    ]
