# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-18 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryentry',
            name='path_model',
            field=models.TextField(null=True),
        ),
    ]
