# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-19 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_categoryentry_path_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryentry',
            name='path_model',
            field=models.TextField(blank=True, null=True),
        ),
    ]
