# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_homepageentry_countdown_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category3DModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoryentry',
            name='path_model',
        ),
        migrations.AddField(
            model_name='categoryentry',
            name='category_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category3DModel'),
        ),
    ]
