# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-17 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20180317_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryentry',
            name='category_model',
        ),
        migrations.AddField(
            model_name='category3dmodel',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.CategoryEntry'),
        ),
    ]
