# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20180317_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='category3dmodel',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
