# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-10 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 10, 15, 2, 3, 962320, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
