# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170710_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='answers',
            field=models.ManyToManyField(to='survey.Choice'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
