# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170710_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='survey.Choice'),
        ),
    ]
