# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-11 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20170710_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='uid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
