# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20170711_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choice_list', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answer_list', to='survey.Choice'),
        ),
    ]
