# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20170711_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textareaquestion',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
