# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_remove_choice_is_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='participant',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
