# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'tr', 'Turkish'), (b'en', 'English')], max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media/photos/team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'tr', 'Turkish'), (b'en', 'English')], max_length=2)),
                ('full_name', models.CharField(max_length=100)),
                ('mission', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Team')),
            ],
        ),
    ]
